Capt/Controllers/InfoController.cs
/*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capt.Controllers
{
	/// <summary>
	/// Controller for the mostly-static general information pages.
	/// </summary>
	public class InfoController : Controller
    {
        
		/// <summary>
		/// Show the "About this site" page.
		/// </summary>
		/// <returns></returns>
		public ActionResult About()
        {
            return View();
        }

		/// <summary>
		/// Show the "Contact us" page.
		/// </summary>
		/// <returns></returns>
		public ActionResult Contact()
		{
			ViewBag.EmailAddress = System.Configuration.ConfigurationManager.AppSettings["EmailsFrom"];

			return View();
		}

		/// <summary>
		/// Show the terms and conditions page.
		/// </summary>
		/// <returns></returns>
		public ActionResult Conditions()
		{
			return View();
		}

		/// <summary>
		/// Show the privacy policy.
		/// </summary>
		/// <returns></returns>
		public ActionResult Privacy()
		{
			return View();
		}

    }
}

Capt/Views/Info/About.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@{
    ViewBag.Title = "About " + ViewBag.SiteName;
}

<h2>About @ViewBag.SiteName</h2>

<p>
    @ViewBag.SiteName is a website where new images are posted at regular intervals, for which users are invited to supply captions.
    The idea was <strike>ripped off from</strike> inspired by <a href="http://www.spinnwebe.com/">SpinnWebe</a>'s
    sadly-defunct <a href="http://www.spinnwebe.com/iadl/">It's a Dysfunctional Life</a>.
</p>

<p>
    @ViewBag.SiteName only uses photos whose authors have licensed them for use by others. If you find your photo here and would 
    rather it weren't, please @Html.ActionLink("contact " + ViewData["SiteName"], "Contact", "Info") to have it removed.
</p>

<p>
    @ViewBag.SiteName is supposed to be fun.
</p>

Capt/Views/Info/Conditions.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@{
    ViewBag.Title = ViewBag.SiteName + "'s Conditions";
}

<h2>@ViewBag.SiteName's Conditions</h2>

<p>
    If you would like to use @ViewBag.SiteName, you must be OK with the following:
</p>
<ul>
    <li>
        Other people will see the captions you submit.  If you do not submit them anonymously, and you 
        unwisely use your real name, people will be able to identify you.
    </li>
    <li>
        @ViewBag.SiteName can and will remove any of your captions at your request, but has no power to 
        remove them from search engines such as <a href="http://www.google.com/">Google</a> and archivers 
        such as <a href="http://www.archive.org">The Wayback Machine</a>, who will most assuredly
        pick your captions up.
    </li>
    <li>
        By submitting a caption to @ViewBag.SiteName, you retain the copyright but agree to license that caption for use under the
        <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)</a>
        license.  (In short, this means anyone can copy and use your caption &mdash; even for commercial purposes &mdash; but must
        attribute it to you and place the same conditions on anything they do with it.)  @ViewBag.SiteName will attribute your caption to you 
        using your @ViewBag.SiteName nickname, or anonymouly if you choose not to use one.
    </li>
    <li>
        If @ViewBag.SiteName suspects you are manipulating the voting system in any way, @ViewBag.SiteName will lock and/or delete your account
        and captions.
    </li>
    <li>
        If @ViewBag.SiteName feels you are a negative influence on the website, @ViewBag.SiteName will lock and/or delete your account and
        captions.
    </li>
    <li>
        In fact, if @ViewBag.SiteName so much as <em>just feels like doing so</em>,
        @ViewBag.SiteName will lock and/or delete your account and captions.  (@ViewBag.SiteName is ruled with an iron fist.)
    </li>
    <li>
        @ViewBag.SiteName is not responsible for you embarrassing yourself on this website or anywhere online.
    </li>
    <li>
        @ViewBag.SiteName is not responsible for someone else embarrassing you on this website or anywhere online.
    </li>
</ul>

Capt/Views/Info/Contact.cshtml
@*
 * Copyright 2011 Sean McCleary
 * 
 * This file is part of capt.
 *
 * capt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * capt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with capt.  If not, see <http://www.gnu.org/licenses/>.
 *@
@{
    ViewBag.Title = "Contact " + ViewBag.SiteName;
}

<h2>Contact</h2>

<p>
    @ViewBag.SiteName does not yet have a fancy contact form you can fill out.
</p>

<p>
    Until it does, you can use the email address <a href="mailto:@ViewBag.EmailAddress">@ViewBag.EmailAddress</a>
</p>

<p>
    @ViewBag.SiteName looks forward to hearing from you.
</p>